In [12]:
from __future__ import print_function
import torch

In [13]:
x = torch.empty(5,3)
print(x)

tensor([[ 0.0000,  2.0000,  0.0000],
        [ 2.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  2.0000,  0.0000]])


In [14]:
x = torch.rand(5,3)
print(x)

tensor([[ 0.9383,  0.5681,  0.8830],
        [ 0.7893,  0.0844,  0.8737],
        [ 0.3445,  0.9983,  0.1322],
        [ 0.9070,  0.4955,  0.5764],
        [ 0.3435,  0.7564,  0.7578]])


In [15]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [16]:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


In [21]:
x = x.new_ones(5, 3, dtype = torch.double)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)


In [22]:
x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[ 1.1423,  0.4861,  1.1925],
        [ 0.4112,  0.2134, -0.7090],
        [-0.0952, -0.4585,  1.5373],
        [-0.3997, -0.4549, -0.9180],
        [-0.1733,  1.0880,  0.9362]])


In [40]:
print(x.size())

torch.Size([5, 3])


In [41]:
y = torch.rand(5, 3)
print(y)

tensor([[ 0.1149,  0.1170,  0.3775],
        [ 0.8126,  0.9098,  0.0095],
        [ 0.3372,  0.4410,  0.9811],
        [ 0.9662,  0.4039,  0.3276],
        [ 0.6877,  0.9031,  0.3633]])


In [42]:
print(x + y)

tensor([[ 2.3995,  1.0892,  2.7626],
        [ 1.6350,  1.3366, -1.4084],
        [ 0.1467, -0.4760,  4.0556],
        [ 0.1667, -0.5058, -1.5083],
        [ 0.3411,  3.0790,  2.2358]])


In [43]:
print(torch.add(x,y))

tensor([[ 2.3995,  1.0892,  2.7626],
        [ 1.6350,  1.3366, -1.4084],
        [ 0.1467, -0.4760,  4.0556],
        [ 0.1667, -0.5058, -1.5083],
        [ 0.3411,  3.0790,  2.2358]])


In [44]:
result = torch.empty(5,3)
print(result)

tensor([[ 0.0000e+00,  2.0000e+00,  0.0000e+00],
        [ 2.0000e+00,  5.6052e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  2.0000e+00, -2.9229e+33]])


In [45]:
torch.add(x, y, out = result)
print(result)

tensor([[ 2.3995,  1.0892,  2.7626],
        [ 1.6350,  1.3366, -1.4084],
        [ 0.1467, -0.4760,  4.0556],
        [ 0.1667, -0.5058, -1.5083],
        [ 0.3411,  3.0790,  2.2358]])


In [46]:
y.add_(x)
print(y)

tensor([[ 2.3995,  1.0892,  2.7626],
        [ 1.6350,  1.3366, -1.4084],
        [ 0.1467, -0.4760,  4.0556],
        [ 0.1667, -0.5058, -1.5083],
        [ 0.3411,  3.0790,  2.2358]])


In [48]:
print(x)

tensor([[ 2.2846,  0.9722,  2.3851],
        [ 0.8224,  0.4268, -1.4179],
        [-0.1905, -0.9170,  3.0745],
        [-0.7994, -0.9097, -1.8359],
        [-0.3466,  2.1759,  1.8724]])


In [57]:
print(x[:,1])

tensor([ 0.9722,  0.4268, -0.9170, -0.9097,  2.1759])


In [58]:
a = torch.randn(4,4)
b = a.view(16)
c = a.view(-1,8)
print(a.size(), b.size(), c.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [61]:
a = torch.randn(1)
print(a)
print(a.item())

tensor([-1.1474])
-1.1474112272262573


In [70]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [71]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [72]:
# changes both the numpy as well as the tensor array as they share a common memory location
a.add_(1)

tensor([ 2.,  2.,  2.,  2.,  2.])

In [73]:
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


In [74]:
import numpy as np
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [75]:
b = torch.from_numpy(a)
print(b)

tensor([ 1.,  1.,  1.,  1.,  1.], dtype=torch.float64)


In [76]:
np.add(a, 1, out = a)

array([2., 2., 2., 2., 2.])

In [77]:
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)
